
spring:
  flyway:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8000/wh_new
    user: admin
    password: admin
  kafka:
    bootstrap-servers: 192.168.1.88:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  datasource:
    dbcp2:
      test-while-idle: true
      validation-query: select 1
      time-between-eviction-runs-millis: 3600000

  security:
    oauth2:
      client:
        registration:
          oauth2-sql-executor:
            client-id: sql-executor
            client-secret: kqQaVi4FySuy7nkfvXQFL4c4XlC5t3Ps
            scope: openid, profile, roles
            authorization-grant-type: authorization_code
            redirect-uri: http://192.168.1.15:8779/login/oauth2/code/sql-executor
        provider:
          oauth2-sql-executor:
            issuer-uri: http://192.168.1.65:8080/realms/sql-trainer
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://192.168.1.65:8080/realms/sql-trainer
server:
  port: 8779


logging:
  level:
    org:
      springframework:
        security:
          trace